<div class="custom-footer-contacts">
    <img src="<?= $block->getViewFileUrl('images/logo-footer.png') ?>" alt="Logo" style="max-width: 150px; margin-bottom: 10px;" />
    <ul style="list-style: none; padding: 0; color: #888;">
        <li><strong>Phone number: </strong>+1 312-239-0843</li>
        <li><strong>Email: </strong>order@perspectiveteam.com</li>
        <li><strong>Address: </strong>Kyiv, 15a Tumaniana</li>
    </ul>
</div>